### ISSUE TITLE
Run MapReduce code in Spark scala project

### ISSUE THREAD

**Issue by xtutran** [xtutran/spark-tutor#1]
Exception in thread "main" java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    org/apache/hadoop/mapred/LocalJobRunner.submitJob(Lorg/apache/hadoop/mapreduce/JobID;Ljava/lang/String;Lorg/apache/hadoop/security/Credentials;)Lorg/apache/hadoop/mapreduce/JobStatus; @29: areturn
  Reason:
    Type 'org/apache/hadoop/mapred/JobStatus' (current frame, stack[0]) is not assignable to 'org/apache/hadoop/mapreduce/JobStatus' (from method signature)
  Current Frame:
    bci: @29
    flags: { }
    locals: { 'org/apache/hadoop/mapred/LocalJobRunner', 'org/apache/hadoop/mapreduce/JobID', 'java/lang/String', 'org/apache/hadoop/security/Credentials', 'org/apache/hadoop/mapred/LocalJobRunner$Job' }
    stack: { 'org/apache/hadoop/mapred/JobStatus' }
  Bytecode:
    0x0000000: bb00 2259 2a2b b800 232c b700 243a 0419
    0x0000010: 04b8 0025 2db6 0026 1904 b800 27b0     

	at org.apache.hadoop.mapred.JobClient.init(JobClient.java:548)
	at org.apache.hadoop.mapred.JobClient.<init>(JobClient.java:520)
	at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:1411)
	at hadoop.mapred.WordCount.run(WordCount.java:131)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at hadoop.mapred.WordCount.main(WordCount.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by xtutran** [comment]
fixed by resolving dependencies
